### ISSUE TITLE
setting subnet for a interface does not possible

### ISSUE THREAD

**Issue by VVelox** [cbsd/cbsd#627]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD nibbles1.vvelox.net 12.2-STABLE FreeBSD 12.2-STABLE stable/12-n232902-2225c9780af vixen42  amd64

CBSD version ( cbsd version ): 13.0.15

Was just looking around it looks like it always assumes that the subnet is a /24. Just tried setting ci_ip4_addr=192.168.14.155/22 and it set it up as...

```
version: 1
config:
    - type: physical
      name: vtnet0
      #mac_address: F2:15:C8:E1:0A:49
      mtu: 1500
      subnets:
      - type: static
        ipv4: true
        ipv6: false
        control: hotplug
        address: 192.168.14.155/24
        gateway: 192.168.14.2
    - type: nameserver
      address:
      - 8.8.8.8
      search:
      - my.domain
```
